flisol_connect/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView

from flisol_connect.views import HomePageView

import foundation


urlpatterns = patterns(
    '',
    url(
        r'^$',
        HomePageView.as_view(),
        name="home"
    ),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^foundation/', include('foundation.urls')),
    url(
        r'^api-auth/',
        include(
            'rest_framework.urls',
            namespace='rest_framework'
        )
    ),

    # API
    url(
        r'^api/',
        include('localapi.urls', namespace='api')
    ),

    (r'^i18n/', include('django.conf.urls.i18n')),

    url(
        '',
        include(
            'social.apps.django_app.urls',
            namespace='social'
        )
    ),

    url(r'', include('user.urls', namespace='user')),

)

localapi/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns
from django.conf.urls import url
from django.conf.urls import include

from localapi import views

from rest_framework.routers import SimpleRouter


urlpatterns = patterns(
    'localapi.views',
    url(
        r'^instancias/$',
        views.FlisolInstanceList.as_view(),
        name='instance',
    ),
    url(
        r'^solicitudes/$',
        views.FlisolInstanceRequestList.as_view(),
        name='request',
    ),
    url(
        r'^inscripciones/$',
        views.FlisolSubscriptionCreation.as_view(),
        name='subscribe',
    ),
)

user/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.conf.urls import patterns
from django.core.urlresolvers import reverse_lazy

from user.forms import CustomAuthenticationForm
from user.forms import CustomPasswordResetForm
from user.forms import CustomSetPasswordForm
from user.views import UserDetailView
from user.views import UserRegistrationView
from user.views import UserUpdateView


urlpatterns = patterns(
    '',

    url(
        r'^login/$',
        'django.contrib.auth.views.login',
        {
            'authentication_form': CustomAuthenticationForm,
        },
        name='login',
    ),

    url(r'^usuario/$', UserDetailView.as_view(), name='me'),

    url(
        r'^logout/$',
        'django.contrib.auth.views.logout',
        {
            'next_page': reverse_lazy('home'),
        },
        name='logout',
    ),


    url(
        r'^password/reset/$',
        'django.contrib.auth.views.password_reset',
        {
            'post_reset_redirect':
            reverse_lazy('user:password_reset_done'),
            'password_reset_form': CustomPasswordResetForm,
        },
        name='password_reset',
    ),
    url(
        r'^password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        name='password_reset_done',
    ),
    url(
        r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {
            'post_reset_redirect':
            reverse_lazy('user:password_reset_complete'),
            'set_password_form': CustomSetPasswordForm,
        },
        name='password_reset_confirm',
    ),
    url(
        r'^password/done/$',
        'django.contrib.auth.views.password_reset_complete',
        name='password_reset_complete',
    ),

    url(
        r'^suscribirse/$',
        UserRegistrationView.as_view(),
        name='registration',
    ),

    url(
        r'^actualizar/$',
        UserUpdateView.as_view(),
        name='profile_update',
    ),

)

flisol_connect/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from datetime import date

from django.views.generic.base import TemplateView
from django.core.cache import cache

from flisol_event.models import FlisolEvent
from flisol_event.models import FlisolInstance
from flisol_event.models import FlisolAttendance

from constance import config


class HomePageView(TemplateView):

    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        days_to_go = cache.get('days_to_go')
        latest_event = FlisolEvent.objects.get(id=config.CURRENT_FLISOL_ID)
        if days_to_go is None:
            days_to_go = (
                latest_event.official_date -
                date.today()
            ).days
            cache.set('days_to_go', days_to_go, 300)
        if days_to_go >= 0:
            context['days_to_go'] = days_to_go

        instances = cache.get('instances')
        if not instances:
            instances = FlisolInstance.objects.filter(
                flisol_event=latest_event
            ).count()
            context['instances'] = instances
        subscriptions = cache.get('subscriptions')
        if not subscriptions:
            from django.contrib.auth import get_user_model
            subscriptions = get_user_model().objects.filter(
                is_active=True
            ).count()
            cache.set('subscriptions', subscriptions)
            context['subscriptions'] = subscriptions
        volunteers = cache.get('volunteers')
        if not volunteers:
            volunteers = FlisolAttendance.objects.exclude(
                role=FlisolAttendance.ATTENDANCE_CHOICES_VISITOR,
            ).filter(flisol_instance__flisol_event=latest_event).count()
            cache.set('volunteers', volunteers)
            context['volunteers'] = volunteers

        return context

flisol_connect/templates/layout/base.html
{% extends "foundation/base.html" %}
{% load staticfiles i18n %}
{% block title %}Flisol{% endblock %}

{% block css %}
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/site.css">
    <link href="{% static "foundation/css/foundation-icons.css" %}" rel="stylesheet"/>
{% endblock css %}

{% block base_body %}
  <nav  data-topbar="" role="navigation" class="top-bar url-instances" data-url-instance-list="{% url 'api:instance' %}">
    <!-- Title -->
    <ul class="title-area">
      <li class="name"><h1><a href="/">Flisol</a></h1></li>

      <!-- Mobile Menu Toggle -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <!-- Top Bar Section -->

      <section class="top-bar-section">
      {% block search %}
      {% endblock %}

      <!-- Top Bar Right Nav Elements -->
      {% block login %}
      <ul class="right">
        <!-- Button -->
        <li>
          {% if user.is_authenticated %}
          <a href="{% url 'user:profile_update' %}" alt="{{ user.email }}" title="{% trans 'update profile' %}"><i class="step fi-torso"></i> {% trans 'Profile' %}</a>
        </li>
        <li><a href="{% url 'user:logout' %}" title="{% trans 'logout' %}"><i class="step fi-x-circle"></i> {% trans 'Logout' %}</a>
        </li>
        <li>
          {% if user.is_staff %}<a class="item" role="button" href="{% url 'admin:index' %}"><i class="step fi-widget style-3"></i> {% trans 'Admin' %}</a>{% endif %}
      {% else %}
          <a href="{% url 'user:login' %}"><i class="step fi-at-sign">{% trans 'Login' %}</i></a>
      {% endif %}
        </li>
      </ul>
      {% endblock login %}
    </section>
    <span></span>
  </nav>
  <div data-alert class="alert-box" style="display:none">
    <div class="alert-content"></div>
    <a href="#" class="close">&times;</a>
  </div>
  {% block content %}
  {% endblock content %}
  <div class="flisol-footer text-center">
      <p>{% trans 'Made with tons of love' %}. <a href="https://github.com/ikks/flisol-connect"><i class="step fi-social-github size-36"></i></a></p>
      <p>2.014 -</p>
      <p>{% trans 'Powered by' %}
        <a href="http://djangoproject.com">Django</a>,
        <a href="http://foundation.zurb.com">Foundation</a>,
        <a href="http://leafletjs.com">Leaflet</a>,
        <a href="http://osm.org">OSM</a>,
        <a href="http://postgresql.org">Postgresql</a>,
        <a href="http://redis.io">Redis</a>.</p>
  </div>
{% endblock %}